// Tests for .agents/scripts/commit-msg.mjs. Run: node --test .agents/scripts/test/commit-msg.test.mjs
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { checkMessage, cleanMessage, HOOK_MARKER } from '../commit-msg.mjs';

const SCRIPT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'commit-msg.mjs');
const ME = { name: 'Dev Person', email: 'dev@example.com' };
const ok = (msg, opts) => assert.equal(checkMessage(msg, opts).ok, true, JSON.stringify(checkMessage(msg, opts)));
const bad = (msg, re, opts) => {
  const r = checkMessage(msg, opts);
  assert.equal(r.ok, false, msg);
  if (re) assert.ok(r.errors.some((e) => re.test(e)), r.errors.join(' | '));
};

test('accepts Conventional Commits headers, bodies and footers', () => {
  ok('feat: add login');
  ok('fix(auth): reject expired tokens');
  ok('feat(api)!: drop v1 endpoints\n\nBREAKING CHANGE: v1 is gone.\nRefs: #12');
  ok('docs: document Gemini Flash setup');
  ok('feat: add AI-assisted search');
  ok('chore(deps): bump vite to 8.1.0\n\nSummaries generated by the build are now cached.');
});

test('accepts messages git writes itself', () => {
  ok("Merge branch 'main' into feat/x");
  ok('Merge pull request #4 from me/branch');
  ok('Revert "feat: add login"\n\nThis reverts commit 1a2b3c4.');
  ok('fixup! feat: add login');
});

test('rejects non-conventional headers and layout problems', () => {
  bad('update stuff', /Conventional Commits/);
  bad('Feat: add login', /Conventional Commits/);
  bad('feat add login', /Conventional Commits/);
  bad('feature: add login', /Conventional Commits/);
  bad('feat(): add login', /Conventional Commits/);
  bad('feat: add login\nbody without blank line', /line 2 must be blank/);
  bad(`feat: ${'x'.repeat(100)}`, /max 100/);
  bad('', /empty/);
  const long = checkMessage(`feat: ${'x'.repeat(70)}`);
  assert.equal(long.ok, true);
  assert.match(long.warnings.join(), /72 recommended/);
});

test('rejects co-author and AI attribution trailers', () => {
  bad('feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>', /Co-authored-by/);
  bad('feat: x\n\nco-authored-by: A Friend <friend@example.com>', /Co-authored-by/);
  bad('feat: x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)', /attribution/);
  bad('feat: x\n\nGenerated with Gemini', /attribution/);
  bad('feat: x\n\nGenerated-by: Antigravity', /attribution trailer/);
  bad('feat: x\n\nAssisted-by: GPT-5', /attribution trailer/);
  bad('feat: x\n\nThis commit was AI-generated.', /attribution/);
  bad('feat: x\n\nContact: bot <noreply@google.com>', /noreply/);
});

test('Signed-off-by is allowed only with the configured identity', () => {
  ok('fix: y\n\nSigned-off-by: Dev Person <dev@example.com>', { identity: ME });
  ok('fix: y\n\nSigned-off-by: Dev Person <DEV@example.com>', { identity: ME });
  bad('fix: y\n\nSigned-off-by: Someone Else <else@example.com>', /own git identity/, { identity: ME });
  bad('fix: y\n\nSigned-off-by: Dev Person <dev@example.com>', /own git identity/);
});

test('comment lines and everything below the scissors line are ignored', () => {
  assert.deepEqual(cleanMessage('# comment\nfeat: a\n\nbody\n# Please enter\n'), ['feat: a', '', 'body']);
  ok('feat: a\n# ------------------------ >8 ------------------------\nCo-authored-by: X <x@example.com>');
});

// ---------------------------------------------------------------- real git commits through the installed hook
let tmp;
let repo;
let env;
const hasGit = spawnSync('git', ['--version'], { encoding: 'utf8' }).status === 0;
const run = (cmd, args, extraEnv = {}) => {
  const r = spawnSync(cmd, args, { cwd: repo, encoding: 'utf8', env: { ...env, ...extraEnv }, windowsHide: true });
  return { code: r.status, out: `${r.stdout || ''}${r.stderr || ''}` };
};
before(() => {
  if (!hasGit) return;
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'commit-msg-test-'));
  repo = path.join(tmp, 'repo');
  fs.mkdirSync(path.join(repo, '.agents', 'scripts'), { recursive: true });
  fs.copyFileSync(SCRIPT, path.join(repo, '.agents', 'scripts', 'commit-msg.mjs'));
  const globalCfg = path.join(tmp, 'gitconfig');
  fs.writeFileSync(globalCfg, '');
  env = { ...process.env, GIT_CONFIG_GLOBAL: globalCfg, GIT_CONFIG_NOSYSTEM: '1' };
  for (const k of ['GIT_AUTHOR_NAME', 'GIT_AUTHOR_EMAIL', 'GIT_COMMITTER_NAME', 'GIT_COMMITTER_EMAIL', 'GIT_CONFIG_PARAMETERS', 'GIT_CONFIG_COUNT', 'GIT_DIR', 'GIT_WORK_TREE', 'FRONTIER_COMMIT_IDENTITY']) delete env[k];
  run('git', ['init', '-q']);
  run('git', ['config', 'user.name', ME.name]);
  run('git', ['config', 'user.email', ME.email]);
});

after(() => {
  if (tmp) fs.rmSync(tmp, { recursive: true, force: true });
});

test('install, status and real commits through the hook', { skip: !hasGit && 'git not installed' }, () => {
  const node = process.execPath;
  const script = path.join(repo, '.agents', 'scripts', 'commit-msg.mjs');
  let r = run(node, [script, 'install', '--dry-run', '--root', repo]);
  assert.equal(r.code, 0, r.out);
  assert.match(r.out, /INSTALL: DRY RUN/);
  r = run(node, [script, 'install', '--root', repo]);
  assert.equal(r.code, 0, r.out);
  assert.match(r.out, /INSTALL: OK/);
  assert.ok(fs.readFileSync(path.join(repo, '.git', 'hooks', 'commit-msg'), 'utf8').includes(HOOK_MARKER));
  r = run(node, [script, 'install', '--root', repo]);
  assert.match(r.out, /unchanged/);
  r = run(node, [script, 'status', '--root', repo]);
  assert.match(r.out, /commit-msg hook: installed/);
  assert.match(r.out, /identity: Dev Person <dev@example.com>/);

  const git = (args, extraEnv = {}) => spawnSync('git', args, { cwd: repo, encoding: 'utf8', env: { ...env, ...extraEnv }, windowsHide: true });
  const change = (n) => {
    fs.appendFileSync(path.join(repo, 'f.txt'), `${n}\n`);
    git(['add', 'f.txt']);
  };
  change(1);
  let c = git(['commit', '-q', '-m', 'feat: first change']);
  assert.equal(c.status, 0, c.stdout + c.stderr);
  change(2);
  c = git(['commit', '-q', '-m', 'did some things']);
  assert.notEqual(c.status, 0, 'non-conventional header must be rejected');
  assert.match(c.stderr, /COMMIT-MSG: FAIL/);
  c = git(['commit', '-q', '-m', 'fix: second', '-m', 'Co-Authored-By: Bot <noreply@anthropic.com>']);
  assert.notEqual(c.status, 0, 'co-author trailer must be rejected');
  c = git(['commit', '-q', '--author', 'Someone Else <else@example.com>', '-m', 'fix: second']);
  assert.notEqual(c.status, 0, '--author must be rejected');
  assert.match(c.stderr, /author is "Someone Else/);
  c = git(['-c', 'user.name=Impostor', 'commit', '-q', '-m', 'fix: second']);
  assert.notEqual(c.status, 0, '-c user.name must be rejected');
  c = git(['commit', '-q', '-m', 'fix: second'], { GIT_COMMITTER_EMAIL: 'bot@example.com' });
  assert.notEqual(c.status, 0, 'committer override must be rejected');
  c = git(['commit', '-q', '-m', 'fix: second']);
  assert.equal(c.status, 0, c.stdout + c.stderr);
  const log = git(['log', '--format=%an <%ae>|%s']).stdout.trim().split('\n');
  assert.deepEqual(log, ['Dev Person <dev@example.com>|fix: second', 'Dev Person <dev@example.com>|feat: first change']);
});

test('install never overwrites a foreign hook', { skip: !hasGit && 'git not installed' }, () => {
  const hook = path.join(repo, '.git', 'hooks', 'commit-msg');
  fs.writeFileSync(hook, '#!/bin/sh\nexit 0\n');
  const r = run(process.execPath, [SCRIPT, 'install', '--root', repo]);
  assert.equal(r.code, 1, r.out);
  assert.match(r.out, /INSTALL: SKIPPED/);
  assert.equal(fs.readFileSync(hook, 'utf8'), '#!/bin/sh\nexit 0\n');
});

test('CLI: --message check and usage errors', () => {
  let r = spawnSync(process.execPath, [SCRIPT, 'check', '--message', 'feat: ok'], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stderr);
  assert.match(r.stderr, /COMMIT-MSG: PASS/);
  r = spawnSync(process.execPath, [SCRIPT, 'check', '--message', 'nope'], { encoding: 'utf8' });
  assert.equal(r.status, 1);
  r = spawnSync(process.execPath, [SCRIPT, 'bogus'], { encoding: 'utf8' });
  assert.equal(r.status, 2);
  r = spawnSync(process.execPath, [SCRIPT, '--help'], { encoding: 'utf8' });
  assert.equal(r.status, 0);
});
